//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTELMANAGEMENTWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodStatu
    {
        public int OrderID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> QuanOr { get; set; }
        public string Status { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
